version: '3'

services:
  app:
    build: .
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./entrypoint.sh
    entrypoint: dockerize -timeout 40s ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    # extra_hosts: 
    #   - "host.docker.internal:127.0.0.1"
    # links:
    #   - mysql-db  
    # depends_on: 
    #   - db
    networks:
      - app-network  

  # db:
  #   build: ./.docker/mysql
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=dev_finances
  #     - MYSQL_ROOT_PASSWORD=root    

  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=dev_finances
  #     - MYSQL_USER=root
  #   volumes:
  #     - ./dbdata:/var/lib/mysql  
  #   ports:
  #     - "3306:3306"
  #   cap_add:
  #     - SYS_NICE    
  #   networks:
  #     - app-network   

networks:
  app-network:
    external: true
    driver: bridge
  

# //etc/hosts 
# //C:\Windows\system32\drivers\etc\hosts

# 127.0.0.1 host.docker.internal