export default {
  ACCESS_PROFILE_ATTR: [
    'id',
    'name',
    'description',
    'type',
    'createdAt',
    'updatedAt',
  ],
  ACCESS_PROFILE_PERMISSION_ATTR: ['id', 'code', 'pt', 'en', 'es', 'fr', 'de'],
  ACCESS_PROFILE_TYPES: ['TAGGEN', 'CORPORATION', 'COMPANY'],
  ACCESS_PROFILE_USER_ATTR: ['email'],
  EXCLUDE_ACCESS_PROFILE_ATTR: ['id', 'createdAt', 'updatedAt', 'deletedAt'],
  PERMISSIONS: {
    ADMIN: 'ADMIN',
    CREATE_ACCESS_PROFILE: 'CREATE_ACCESS_PROFILE',
    EDIT_ACCESS_PROFILE: 'EDIT_ACCESS_PROFILE',
    REMOVE_ACCESS_PROFILE: 'REMOVE_ACCESS_PROFILE',
    LIST_ACCESS_PROFILE: 'LIST_ACCESS_PROFILE',
   
    CREATE_COMPANY: 'CREATE_COMPANY',
    EDIT_COMPANY: 'EDIT_COMPANY',
    REMOVE_COMPANY: 'REMOVE_COMPANY',
    LIST_COMPANY: 'LIST_COMPANY',
   
    CREATE_USER: 'CREATE_USER',
    EDIT_USER: 'EDIT_USER',
    REMOVE_USER: 'REMOVE_USER',
    LIST_USER: 'LIST_USER',
  },
};
